import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-8 min-h-screen flex flex-col">
          <p className="text-2xl text-center font-[family-name:var(--font-geist-mono)]">Abhinav Manoj</p>
          <p className="text-1xl text-center font-[family-name:var(--font-geist-mono)] text-grey">Front-End Developer</p>
        
          <div className={"flex grow items-center justify-center"}>
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
